import argparse
import re
from pathlib import Path

import capnp

from wmfs_plugin.metadata import (
    OperationMetadata,
    PluginMetadata,
    metadata_fingerprint,
    metadata_from_reader,
)
from wmfs_plugin.schema import schema_root

_FINGERPRINT_PATTERN = re.compile(r"(fingerprint\s*=\s*)0x[0-9a-fA-F]+")
_CPP_SCALARS = {
    "boolean": ("ScalarArgument::BOOLEAN", "getBoolean"),
    "float64": ("ScalarArgument::FLOAT64", "getFloat64"),
    "int64": ("ScalarArgument::INT64", "getInt64"),
    "text": ("ScalarArgument::TEXT", "getText"),
}


def generate(
    schema_path: Path,
    python_output: Path,
    cpp_output: Path,
    *,
    check: bool = False,
) -> int:
    schema = capnp.load(
        str(schema_path),
        imports=[str(schema_root()), str(schema_path.parent.parent)],
    )
    metadata = metadata_from_reader(schema.pluginMetadata, validate_fingerprint=False)
    fingerprint = metadata_fingerprint(metadata)
    schema_text = schema_path.read_text()
    expected_schema, replacements = _FINGERPRINT_PATTERN.subn(
        rf"\g<1>0x{fingerprint:016x}", schema_text, count=1
    )
    if replacements != 1:
        raise ValueError("Schema must declare exactly one metadata fingerprint")

    outputs = {
        schema_path: expected_schema,
        python_output: _render_python(metadata),
        cpp_output: _render_cpp(metadata, fingerprint),
    }
    stale = [path for path, content in outputs.items() if _read(path) != content]
    if check:
        if stale:
            paths = ", ".join(str(path) for path in stale)
            raise RuntimeError(
                f"Generated operation transport artifacts are stale: {paths}"
            )
        return fingerprint
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return fingerprint


def _read(path: Path) -> str | None:
    try:
        return path.read_text()
    except FileNotFoundError:
        return None


def _render_python(metadata: PluginMetadata) -> str:
    lines = [
        "# Generated by wmfs_plugin.codegen. Do not edit.",
        "from collections.abc import Callable, Mapping",
        "",
        "from wmfs_plugin import InvocationContext, OperationHandler",
        "",
        f'PLUGIN_VERSION = "{metadata.version}"',
        "Implementation = Callable[..., None]",
        "",
        "",
    ]
    for operation in metadata.operations:
        lines.extend(_render_python_adapter(operation))
    lines.extend(
        [
            "_OPERATION_NAMES = frozenset(",
            "    {",
            *(f'        "{item.name}",' for item in metadata.operations),
            "    }",
            ")",
            "",
            "",
            "def bind_operations(",
            "    implementations: Mapping[str, Implementation],",
            ") -> dict[str, OperationHandler]:",
            "    if set(implementations) != _OPERATION_NAMES:",
            "        missing = sorted(_OPERATION_NAMES - set(implementations))",
            "        unknown = sorted(set(implementations) - _OPERATION_NAMES)",
            "        raise ValueError(",
            '            f"Implementations do not match generated metadata: "',
            '            f"missing={missing}, unknown={unknown}"',
            "        )",
            "    return {",
        ]
    )
    for operation in metadata.operations:
        lines.append(
            f'        "{operation.name}": _adapt_{operation.name}('
            f'implementations["{operation.name}"]),'
        )
    lines.extend(["    }", ""])
    return "\n".join(lines)


def _render_python_adapter(operation: OperationMetadata) -> list[str]:
    arguments = [
        f"context.inputs[{index}]" for index in range(len(operation.tensor_inputs))
    ]
    arguments.extend(
        f"context.scalars[{index}]" for index in range(len(operation.scalar_parameters))
    )
    arguments.extend(
        f"context.outputs[{index}]" for index in range(len(operation.tensor_outputs))
    )
    lines = [
        f"def _adapt_{operation.name}(implementation: Implementation) -> OperationHandler:",
        "    def handler(context: InvocationContext) -> None:",
    ]
    if len(", ".join(arguments)) <= 70:
        lines.append(f"        implementation({', '.join(arguments)})")
    else:
        lines.append("        implementation(")
        lines.extend(f"            {argument}," for argument in arguments)
        lines.append("        )")
    lines.extend(["", "    return handler", "", ""])
    return lines


def _render_cpp(metadata: PluginMetadata, fingerprint: int) -> str:
    lines = [
        "// Generated by wmfs_plugin.codegen. Do not edit.",
        f'constexpr char REFERENCE_PLUGIN_VERSION[] = "{metadata.version}";',
        f"constexpr std::uint64_t REFERENCE_METADATA_FINGERPRINT = 0x{fingerprint:016x}ULL;",
        "",
        "void execute_known(std::uint32_t operation_id, std::vector<TensorLease> &inputs,",
        "                   std::vector<TensorLease> &outputs,",
        "                   capnp::List<ScalarArgument>::Reader scalars) {",
        "    switch (operation_id) {",
    ]
    for operation in metadata.operations:
        lines.extend(_render_cpp_case(operation))
    lines.extend(
        [
            "    default:",
            '        throw std::invalid_argument("Unknown operation ID " +',
            "                                    std::to_string(operation_id));",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def _render_cpp_case(operation: OperationMetadata) -> list[str]:
    input_count = len(operation.tensor_inputs)
    output_count = len(operation.tensor_outputs)
    scalar_count = len(operation.scalar_parameters)
    lines = [
        f"    case {operation.operation_id}:",
        f"        require(inputs.size() == {input_count} && outputs.size() == {output_count} &&",
        f"                    scalars.size() == {scalar_count},",
        f'                "Invalid {operation.name} invocation");',
    ]
    for index, scalar in enumerate(operation.scalar_parameters):
        enum_name, _getter = _CPP_SCALARS[scalar.kind]
        lines.extend(
            [
                f"        require(scalars[{index}].getParameter() == {index} &&",
                f"                    scalars[{index}].which() == {enum_name},",
                '                "Scalar argument does not match operation metadata");',
            ]
        )
    arguments = [f"inputs[{index}].tensor()" for index in range(input_count)]
    arguments.extend(
        f"scalars[{index}].{_CPP_SCALARS[scalar.kind][1]}()"
        for index, scalar in enumerate(operation.scalar_parameters)
    )
    arguments.extend(f"outputs[{index}].tensor()" for index in range(output_count))
    prefix = f"        {operation.name}_out("
    current = prefix
    continuation = " " * len(prefix)
    for index, argument in enumerate(arguments):
        token = argument + (");" if index == len(arguments) - 1 else ",")
        separator = "" if current == prefix else " "
        if len(current) + len(separator) + len(token) > 80:
            lines.append(current)
            current = continuation + token
        else:
            current += separator + token
    lines.append(current)
    lines.append("        return;")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate transport adapters from validated plugin metadata"
    )
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--python-output", type=Path, required=True)
    parser.add_argument("--cpp-output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generate(
        arguments.schema,
        arguments.python_output,
        arguments.cpp_output,
        check=arguments.check,
    )


if __name__ == "__main__":
    main()
