/* Generated by wmfs-tool. Do not edit. */
#ifndef WMFS_PLUGIN_ABI_H
#define WMFS_PLUGIN_ABI_H

#include <stdint.h>

#define WMFS_PLUGIN_ABI_VERSION UINT32_C(1)
#define WMFS_PLUGIN_MAX_RANK UINT32_C(16)
#define WMFS_PLUGIN_MAX_INPUTS UINT32_C(16)
#define WMFS_PLUGIN_MAX_OUTPUTS UINT32_C(8)

#ifdef __cplusplus
extern "C" {
#endif

typedef enum wmfs_status_v1 {
    WMFS_STATUS_OK = 0,
    WMFS_STATUS_INVALID_ARGUMENT = 1,
    WMFS_STATUS_UNSUPPORTED = 2,
    WMFS_STATUS_INTERNAL_ERROR = 3
} wmfs_status_v1;

typedef enum wmfs_dtype_v1 {
    WMFS_DTYPE_INVALID = 0,
    WMFS_DTYPE_BOOL = 1,
    WMFS_DTYPE_INT8 = 2,
    WMFS_DTYPE_UINT8 = 3,
    WMFS_DTYPE_INT16 = 4,
    WMFS_DTYPE_INT32 = 5,
    WMFS_DTYPE_INT64 = 6,
    WMFS_DTYPE_FLOAT16 = 7,
    WMFS_DTYPE_FLOAT32 = 8,
    WMFS_DTYPE_FLOAT64 = 9,
    WMFS_DTYPE_BFLOAT16 = 10
} wmfs_dtype_v1;

typedef enum wmfs_scalar_kind_v1 {
    WMFS_SCALAR_BOOLEAN = 1,
    WMFS_SCALAR_FLOAT64 = 2,
    WMFS_SCALAR_INT64 = 3,
    WMFS_SCALAR_TEXT = 4
} wmfs_scalar_kind_v1;

typedef struct wmfs_tensor_v1 {
    uint32_t struct_size;
    uint32_t flags;
    uint64_t buffer_id;
    uint64_t buffer_generation;
    uint64_t byte_offset;
    uint64_t byte_length;
    uint32_t dtype;
    uint32_t rank;
    int64_t shape[16];
    int64_t strides[16];
    void *data;
} wmfs_tensor_v1;

typedef struct wmfs_scalar_v1 {
    uint32_t struct_size;
    uint32_t parameter_index;
    uint32_t kind;
    uint32_t reserved;
    uint64_t bits;
    const char *text;
    uint64_t text_length;
} wmfs_scalar_v1;

typedef struct wmfs_invocation_v1 {
    uint32_t struct_size;
    uint32_t operation_id;
    uint64_t submission_id;
    uint32_t input_count;
    uint32_t output_count;
    uint32_t scalar_count;
    uint32_t reserved;
    const wmfs_tensor_v1 *inputs;
    wmfs_tensor_v1 *outputs;
    const wmfs_scalar_v1 *scalars;
} wmfs_invocation_v1;

typedef int32_t (*wmfs_dispatch_v1)(const wmfs_invocation_v1 *invocation);

typedef struct wmfs_plugin_api_v1 {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t protocol_version;
    uint32_t reserved;
    const char *plugin_name;
    const char *plugin_version;
    const char *interface_fingerprint;
    wmfs_dispatch_v1 dispatch;
} wmfs_plugin_api_v1;

typedef const wmfs_plugin_api_v1 *(*wmfs_get_plugin_api_v1)(
    uint32_t abi_version);

#ifdef __cplusplus
}
#endif
#endif
