import json
import runpy
import shutil
import subprocess
from pathlib import Path

import pytest

from wmfs_tool.cli import main
from wmfs_tool.generator import generate

ROOT = Path(__file__).parents[3]
INTERFACE = ROOT / "plugins/reference/interface.toml"
MODE_NEUTRAL_INTERFACE = ROOT / "tests/fixtures/mode_neutral/interface.toml"


def test_generation_is_deterministic_and_check_detects_stale(tmp_path: Path) -> None:
    first = generate(INTERFACE, tmp_path)
    before = {
        path.relative_to(tmp_path): path.read_bytes()
        for path in tmp_path.rglob("*")
        if path.is_file()
    }

    assert generate(INTERFACE, tmp_path, check=True) == first
    generate(INTERFACE, tmp_path)
    after = {
        path.relative_to(tmp_path): path.read_bytes()
        for path in tmp_path.rglob("*")
        if path.is_file()
    }
    assert after == before

    manifest = json.loads((tmp_path / "manifest.json").read_text())
    assert manifest["interfaceFingerprint"] == f"sha256:{first}"
    assert manifest["operationCount"] == 6
    assert manifest["startupCapabilities"] == 255
    assert manifest["deployment"]["worker"] == "wmfs-reference-worker"
    assert manifest["controlAbiVersion"] == 1
    assert "interface" not in manifest["deployment"]
    assert "schema" not in manifest["deployment"]
    assert manifest["metadataFingerprint"] == "0xf6ed5672a8a496cb"
    assert manifest["formatVersion"] == 2
    assert manifest["generator"] == "wmfs-tool/2"
    assert manifest["operations"][0]["dtype_variables"][0]["name"] == "T"
    assert manifest["operations"][5]["scalars"][0]["enum_values"] == [
        "rowMajor",
        "columnMajor",
    ]
    assert manifest["operations"][5]["outputs"][0]["allocation"] == "dynamic"
    assert manifest["lifecycle"] == {"initialize": True, "shutdown": True}
    configuration = manifest["configuration"]
    assert configuration["schemaVersion"] == 1
    assert configuration["encoding"] == "wmfs-configuration-schema-v1"
    assert configuration["fingerprint"].startswith("sha256:")
    assert configuration["schema"]["additionalProperties"] is False
    assert configuration["schema"]["properties"]["solver"]["required"] == ["algorithm"]
    assert configuration["examples"]["throughput"]["threads"] == 8
    stub = (tmp_path / "python/wmfs_reference/interface.pyi").read_text()
    assert "class IndexOrder(IntEnum):" in stub
    assert "full_matrices: bool = True" in stub
    assert "-> tuple[torch.Tensor, torch.Tensor, torch.Tensor]" in stub
    assert "out: tuple[torch.Tensor, torch.Tensor, torch.Tensor]" in stub
    assert "class Configuration(TypedDict, total=False):" in stub
    assert 'PrecisionValue = Literal["fast", "balanced", "accurate"]' in stub
    assert (
        (tmp_path.parent / "wmfs_reference" / "_generated.py")
        .read_text()
        .startswith("# Generated by wmfs-tool.")
    )
    metadata = (tmp_path / "python/wmfs_reference/interface.py").read_text()
    assert "OPERATION_COUNT = 6" in metadata
    assert "STARTUP_CAPABILITIES = 255" in metadata
    assert "INTERFACE_FINGERPRINT_SHA256 = bytes.fromhex" in metadata
    header = (tmp_path / "include/wmfs/reference_plugin.hpp").read_text()
    assert "WMFS_REFERENCE_OPERATION_COUNT UINT32_C(6)" in header
    assert "WMFS_REFERENCE_STARTUP_CAPABILITIES UINT64_C(255)" in header
    assert "interface_fingerprint_sha256[32]" in header
    assert bytes.fromhex(first) == bytes.fromhex(
        manifest["interfaceFingerprint"].removeprefix("sha256:")
    )
    generated_identity = runpy.run_path(
        str(tmp_path / "python/wmfs_reference/interface.py")
    )
    assert generated_identity["INTERFACE_FINGERPRINT_SHA256"] == bytes.fromhex(first)
    assert generated_identity["CONFIGURATION_FINGERPRINT_SHA256"] == bytes.fromhex(
        configuration["fingerprint"].removeprefix("sha256:")
    )
    assert generated_identity["OPERATION_COUNT"] == manifest["operationCount"]
    assert generated_identity["STARTUP_CAPABILITIES"] == manifest["startupCapabilities"]

    (tmp_path / "manifest.json").write_text("stale")
    with pytest.raises(RuntimeError, match="manifest.json"):
        generate(INTERFACE, tmp_path, check=True)


def test_non_reference_fixture_uses_the_same_artifact_layout(tmp_path: Path) -> None:
    generate(MODE_NEUTRAL_INTERFACE, tmp_path)
    manifest = json.loads((tmp_path / "manifest.json").read_text())

    assert manifest["plugin"]["name"] == "mode_neutral"
    assert manifest["deployment"]["localProvider"] == "wmfs_mode_neutral.kernels"
    assert manifest["deployment"]["entrySymbol"] == ("wmfs_mode_neutral_plugin_get_api")
    assert [operation["name"] for operation in manifest["operations"]] == ["scale"]
    assert (tmp_path / "src/mode_neutral_plugin_stub.cpp").is_file()
    assert not tuple(tmp_path.glob("*local*"))
    assert not tuple(tmp_path.glob("*bundled*"))
    assert not tuple(tmp_path.glob("*isolated*"))


def test_cli_reports_validation_errors(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    invalid = tmp_path / "invalid.toml"
    invalid.write_text("format_version = 1\n")

    assert (
        main(["generate", "--interface", str(invalid), "--output", str(tmp_path)]) == 1
    )
    assert "missing required field" in capsys.readouterr().err


def test_generated_headers_and_stub_compile_as_cpp11(tmp_path: Path) -> None:
    compiler = shutil.which("c++") or shutil.which("g++") or shutil.which("clang++")
    if compiler is None:
        pytest.skip("no C++ compiler is available")
    generate(INTERFACE, tmp_path)
    source = tmp_path / "compile.cpp"
    source.write_text(
        "#include <wmfs/reference_plugin.hpp>\n"
        'static_assert(WMFS_REFERENCE_ABI_VERSION == 1, "ABI");\n'
        'static_assert(WMFS_REFERENCE_CONFIGURATION_SCHEMA_VERSION == 1, "config");\n'
        'static_assert(WMFS_REFERENCE_HAS_INITIALIZE, "initialize");\n'
        "static_assert(wmfs::reference::configuration::Precision::accurate != "
        'wmfs::reference::configuration::Precision::fast, "config enum");\n'
        "namespace wmfs { namespace reference {\n"
        "#define WMFS_IMPL(operation, type) template <> std::int32_t "
        "operation##_typed<type>(dtype_tag<type>, const wmfs_invocation_v1 *) "
        "{ return WMFS_STATUS_OK; }\n"
        "#define WMFS_NUMERIC(operation) WMFS_IMPL(operation, float) "
        "WMFS_IMPL(operation, double) WMFS_IMPL(operation, std::int64_t) "
        "WMFS_IMPL(operation, std::uint8_t)\n"
        "WMFS_NUMERIC(matmul) WMFS_IMPL(svd, float) WMFS_IMPL(svd, double) "
        "WMFS_NUMERIC(add_scalar) WMFS_NUMERIC(matmul_vjp) "
        "WMFS_NUMERIC(add_scalar_vjp) WMFS_NUMERIC(nonzero)\n"
        "#define WMFS_PLAN_IMPL(type) template <> std::int32_t "
        "nonzero_plan_typed<type>(dtype_tag<type>, const wmfs_invocation_v1 *, "
        "wmfs_output_plan_v1 *, std::uint32_t, std::uint32_t *) "
        "{ return WMFS_STATUS_OK; }\n"
        "WMFS_PLAN_IMPL(float) WMFS_PLAN_IMPL(double) "
        "WMFS_PLAN_IMPL(std::int64_t) WMFS_PLAN_IMPL(std::uint8_t)\n"
        "} }\n"
        "int main() {\n"
        "  const wmfs_plugin_api_v1 *api = wmfs_reference_plugin_get_api(1);\n"
        "  wmfs_tensor_v1 inputs[2] = {}; wmfs_tensor_v1 outputs[1] = {};\n"
        "  wmfs_invocation_v1 invocation = {}; invocation.struct_size = sizeof(invocation);\n"
        "  invocation.operation_id = 1; invocation.input_count = 2; "
        "invocation.output_count = 1; invocation.inputs = inputs; invocation.outputs = outputs;\n"
        "  const uint32_t dtypes[] = {WMFS_DTYPE_FLOAT32, WMFS_DTYPE_FLOAT64, "
        "WMFS_DTYPE_INT64, WMFS_DTYPE_UINT8};\n"
        "  for (unsigned i = 0; i < 4; ++i) { inputs[0].dtype = inputs[1].dtype = "
        "outputs[0].dtype = dtypes[i]; if (api->dispatch(&invocation) != WMFS_STATUS_OK) return 1; }\n"
        "  inputs[1].dtype = WMFS_DTYPE_FLOAT64; inputs[0].dtype = outputs[0].dtype = "
        "WMFS_DTYPE_FLOAT32; if (api->dispatch(&invocation) != WMFS_STATUS_INVALID_ARGUMENT) return 2;\n"
        "  wmfs_scalar_v1 scalar = {}; scalar.kind = WMFS_SCALAR_INT64; "
        "invocation.operation_id = 6; invocation.input_count = 1; invocation.scalar_count = 1; "
        "invocation.scalars = &scalar; inputs[0].dtype = WMFS_DTYPE_FLOAT32; outputs[0].dtype = "
        "WMFS_DTYPE_INT64; if (api->dispatch(&invocation) != WMFS_STATUS_OK) return 3; "
        "scalar.bits = 2; return api->dispatch(&invocation) == WMFS_STATUS_INVALID_ARGUMENT ? 0 : 4;\n"
        "}\n"
    )
    subprocess.run(
        [
            compiler,
            "-std=c++11",
            "-Werror",
            "-I",
            str(tmp_path / "include"),
            "-c",
            str(source),
            "-o",
            str(tmp_path / "compile.o"),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run(
        [
            compiler,
            "-std=c++11",
            "-Werror",
            "-I",
            str(tmp_path / "include"),
            "-c",
            str(tmp_path / "src/reference_plugin_stub.cpp"),
            "-o",
            str(tmp_path / "stub.o"),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    executable = tmp_path / "generated-dispatch-test"
    subprocess.run(
        [
            compiler,
            str(tmp_path / "compile.o"),
            str(tmp_path / "stub.o"),
            "-o",
            str(executable),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run([str(executable)], check=True, capture_output=True, text=True)


def test_configuration_fingerprint_is_independent_from_interface_metadata(
    tmp_path: Path,
) -> None:
    first = tmp_path / "first"
    second = tmp_path / "second"
    changed = tmp_path / "changed.toml"
    source = INTERFACE.read_text(encoding="utf-8")
    changed.write_text(
        source.replace("default = 1\nminimum = 1", "default = 2\nminimum = 1", 1)
    )

    first_interface = generate(INTERFACE, first)
    second_interface = generate(changed, second)
    first_manifest = json.loads((first / "manifest.json").read_text())
    second_manifest = json.loads((second / "manifest.json").read_text())

    assert second_interface == first_interface
    assert (
        second_manifest["metadataFingerprint"] == first_manifest["metadataFingerprint"]
    )
    assert (
        second_manifest["configuration"]["fingerprint"]
        != first_manifest["configuration"]["fingerprint"]
    )


def test_non_configurable_plugin_generates_null_configuration(tmp_path: Path) -> None:
    source = INTERFACE.read_text(encoding="utf-8")
    start = source.index("[configuration]")
    end = source.index("[[enums]]")
    path = tmp_path / "interface.toml"
    path.write_text(source[:start] + source[end:])

    generate(path, tmp_path / "generated")

    manifest = json.loads((tmp_path / "generated/manifest.json").read_text())
    metadata = (tmp_path / "generated/python/wmfs_reference/interface.py").read_text()
    header = (tmp_path / "generated/include/wmfs/reference_plugin.hpp").read_text()
    assert manifest["configuration"] is None
    assert "CONFIGURATION_SCHEMA_VERSION = None" in metadata
    assert "CONFIGURATION_FINGERPRINT = None" in metadata
    assert "CONFIGURATION_SCHEMA_VERSION UINT32_C(0)" in header
