import json
import shutil
import subprocess
from pathlib import Path

import pytest

from wmfs_tool.cli import main
from wmfs_tool.generator import generate

ROOT = Path(__file__).parents[3]
INTERFACE = ROOT / "plugins/reference/interface.toml"


def test_generation_is_deterministic_and_check_detects_stale(tmp_path: Path) -> None:
    first = generate(INTERFACE, tmp_path)
    before = {
        path.relative_to(tmp_path): path.read_bytes()
        for path in tmp_path.rglob("*")
        if path.is_file()
    }

    assert generate(INTERFACE, tmp_path, check=True) == first
    generate(INTERFACE, tmp_path)
    after = {
        path.relative_to(tmp_path): path.read_bytes()
        for path in tmp_path.rglob("*")
        if path.is_file()
    }
    assert after == before

    manifest = json.loads((tmp_path / "manifest.json").read_text())
    assert manifest["interfaceFingerprint"] == f"sha256:{first}"
    assert manifest["operationCount"] == 6
    assert manifest["deployment"]["worker"] == "wmfs-reference-worker"
    assert manifest["deployment"]["interface"] == "ReferencePlugin"
    assert manifest["metadataFingerprint"] == "0xf6ed5672a8a496cb"
    assert manifest["formatVersion"] == 2
    assert manifest["generator"] == "wmfs-tool/2"
    assert manifest["operations"][0]["dtype_variables"][0]["name"] == "T"
    assert manifest["operations"][5]["scalars"][0]["enum_values"] == [
        "rowMajor",
        "columnMajor",
    ]
    assert manifest["operations"][5]["outputs"][0]["allocation"] == "dynamic"
    assert (
        (tmp_path / "reference_dispatch.inc")
        .read_text()
        .startswith("// Generated by wmfs-tool.")
    )
    stub = (tmp_path / "python/wmfs_reference/interface.pyi").read_text()
    assert "class IndexOrder(IntEnum):" in stub
    assert "full_matrices: bool = True" in stub
    assert "-> tuple[torch.Tensor, torch.Tensor, torch.Tensor]" in stub
    assert "out: tuple[torch.Tensor, torch.Tensor, torch.Tensor]" in stub
    assert (
        (tmp_path.parent / "wmfs_reference" / "_generated.py")
        .read_text()
        .startswith("# Generated by wmfs-tool.")
    )

    (tmp_path / "manifest.json").write_text("stale")
    with pytest.raises(RuntimeError, match="manifest.json"):
        generate(INTERFACE, tmp_path, check=True)


def test_cli_reports_validation_errors(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    invalid = tmp_path / "invalid.toml"
    invalid.write_text("format_version = 1\n")

    assert (
        main(["generate", "--interface", str(invalid), "--output", str(tmp_path)]) == 1
    )
    assert "missing required field" in capsys.readouterr().err


def test_generated_headers_and_stub_compile_as_cpp11(tmp_path: Path) -> None:
    compiler = shutil.which("c++") or shutil.which("g++") or shutil.which("clang++")
    if compiler is None:
        pytest.skip("no C++ compiler is available")
    generate(INTERFACE, tmp_path)
    source = tmp_path / "compile.cpp"
    source.write_text(
        "#include <wmfs/reference_plugin.hpp>\n"
        'static_assert(WMFS_REFERENCE_ABI_VERSION == 1, "ABI");\n'
        "namespace wmfs { namespace reference {\n"
        "#define WMFS_IMPL(operation, type) template <> std::int32_t "
        "operation##_typed<type>(dtype_tag<type>, const wmfs_invocation_v1 *) "
        "{ return WMFS_STATUS_OK; }\n"
        "#define WMFS_NUMERIC(operation) WMFS_IMPL(operation, float) "
        "WMFS_IMPL(operation, double) WMFS_IMPL(operation, std::int64_t) "
        "WMFS_IMPL(operation, std::uint8_t)\n"
        "WMFS_NUMERIC(matmul) WMFS_IMPL(svd, float) WMFS_IMPL(svd, double) "
        "WMFS_NUMERIC(add_scalar) WMFS_NUMERIC(matmul_vjp) "
        "WMFS_NUMERIC(add_scalar_vjp) WMFS_NUMERIC(nonzero)\n"
        "} }\n"
        "int main() {\n"
        "  const wmfs_plugin_api_v1 *api = wmfs_plugin_get_api(1);\n"
        "  wmfs_tensor_v1 inputs[2] = {}; wmfs_tensor_v1 outputs[1] = {};\n"
        "  wmfs_invocation_v1 invocation = {}; invocation.struct_size = sizeof(invocation);\n"
        "  invocation.operation_id = 1; invocation.input_count = 2; "
        "invocation.output_count = 1; invocation.inputs = inputs; invocation.outputs = outputs;\n"
        "  const uint32_t dtypes[] = {WMFS_DTYPE_FLOAT32, WMFS_DTYPE_FLOAT64, "
        "WMFS_DTYPE_INT64, WMFS_DTYPE_UINT8};\n"
        "  for (unsigned i = 0; i < 4; ++i) { inputs[0].dtype = inputs[1].dtype = "
        "outputs[0].dtype = dtypes[i]; if (api->dispatch(&invocation) != WMFS_STATUS_OK) return 1; }\n"
        "  inputs[1].dtype = WMFS_DTYPE_FLOAT64; inputs[0].dtype = outputs[0].dtype = "
        "WMFS_DTYPE_FLOAT32; if (api->dispatch(&invocation) != WMFS_STATUS_INVALID_ARGUMENT) return 2;\n"
        "  wmfs_scalar_v1 scalar = {}; scalar.kind = WMFS_SCALAR_INT64; "
        "invocation.operation_id = 6; invocation.input_count = 1; invocation.scalar_count = 1; "
        "invocation.scalars = &scalar; inputs[0].dtype = WMFS_DTYPE_FLOAT32; outputs[0].dtype = "
        "WMFS_DTYPE_INT64; if (api->dispatch(&invocation) != WMFS_STATUS_OK) return 3; "
        "scalar.bits = 2; return api->dispatch(&invocation) == WMFS_STATUS_INVALID_ARGUMENT ? 0 : 4;\n"
        "}\n"
    )
    subprocess.run(
        [
            compiler,
            "-std=c++11",
            "-Werror",
            "-I",
            str(tmp_path / "include"),
            "-c",
            str(source),
            "-o",
            str(tmp_path / "compile.o"),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run(
        [
            compiler,
            "-std=c++11",
            "-Werror",
            "-I",
            str(tmp_path / "include"),
            "-c",
            str(tmp_path / "src/reference_plugin_stub.cpp"),
            "-o",
            str(tmp_path / "stub.o"),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    executable = tmp_path / "generated-dispatch-test"
    subprocess.run(
        [
            compiler,
            str(tmp_path / "compile.o"),
            str(tmp_path / "stub.o"),
            "-o",
            str(executable),
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    subprocess.run([str(executable)], check=True, capture_output=True, text=True)
