# Generated by wmfs_plugin.codegen. Do not edit.
from collections.abc import Callable, Mapping
from types import MappingProxyType
from typing import NamedTuple

from wmfs_plugin import InvocationContext, OperationHandler

PLUGIN_NAME = "reference"
API_NAMESPACE = PLUGIN_NAME
PLUGIN_VERSION = "0.1.0"
PROTOCOL_VERSION = 11
METADATA_FINGERPRINT = 0x549FB18B7A4B6C75


class GeneratedOperation(NamedTuple):
    operation_id: int
    name: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    scalars: tuple[str, ...]
    dynamic_outputs: tuple[str, ...]
    internal: bool


OPERATIONS = (
    GeneratedOperation(
        1,
        "matmul",
        ("a", "b"),
        ("result",),
        (),
        (),
        False,
    ),
    GeneratedOperation(
        2,
        "svd",
        ("a",),
        ("u", "s", "vh"),
        ("fullMatrices",),
        (),
        False,
    ),
    GeneratedOperation(
        3,
        "add_scalar",
        ("a",),
        ("result",),
        ("value",),
        (),
        False,
    ),
    GeneratedOperation(
        4,
        "matmul_vjp",
        ("a", "b", "resultCotangent"),
        ("aGradient", "bGradient"),
        (),
        (),
        True,
    ),
    GeneratedOperation(
        5,
        "add_scalar_vjp",
        ("resultCotangent",),
        ("aGradient",),
        (),
        (),
        True,
    ),
    GeneratedOperation(
        6,
        "nonzero",
        ("a",),
        ("indices",),
        (),
        ("indices",),
        False,
    ),
)
OPERATIONS_BY_NAME = MappingProxyType({item.name: item for item in OPERATIONS})
Implementation = Callable[..., None]


def _adapt_matmul(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.inputs[1], context.outputs[0])

    return handler


def _adapt_svd(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(
            context.inputs[0],
            context.scalars[0],
            context.outputs[0],
            context.outputs[1],
            context.outputs[2],
        )

    return handler


def _adapt_add_scalar(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.scalars[0], context.outputs[0])

    return handler


def _adapt_matmul_vjp(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(
            context.inputs[0],
            context.inputs[1],
            context.inputs[2],
            context.outputs[0],
            context.outputs[1],
        )

    return handler


def _adapt_add_scalar_vjp(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.outputs[0])

    return handler


def _adapt_nonzero(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.outputs[0])

    return handler


_OPERATION_NAMES = frozenset(
    {
        "matmul",
        "svd",
        "add_scalar",
        "matmul_vjp",
        "add_scalar_vjp",
        "nonzero",
    }
)


def bind_operations(
    implementations: Mapping[str, Implementation],
) -> dict[str, OperationHandler]:
    if set(implementations) != _OPERATION_NAMES:
        missing = sorted(_OPERATION_NAMES - set(implementations))
        unknown = sorted(set(implementations) - _OPERATION_NAMES)
        raise ValueError(
            f"Implementations do not match generated metadata: "
            f"missing={missing}, unknown={unknown}"
        )
    return {
        "matmul": _adapt_matmul(implementations["matmul"]),
        "svd": _adapt_svd(implementations["svd"]),
        "add_scalar": _adapt_add_scalar(implementations["add_scalar"]),
        "matmul_vjp": _adapt_matmul_vjp(implementations["matmul_vjp"]),
        "add_scalar_vjp": _adapt_add_scalar_vjp(implementations["add_scalar_vjp"]),
        "nonzero": _adapt_nonzero(implementations["nonzero"]),
    }
