# Generated by wmfs-tool. Do not edit.
from collections.abc import Callable, Mapping
from types import MappingProxyType
from typing import TYPE_CHECKING, NamedTuple

from wmfs_plugin.invocation import InvocationContext

if TYPE_CHECKING:
    from wmfs_plugin.worker import OperationHandler
else:
    OperationHandler = Callable[[InvocationContext], None]

PLUGIN_NAME = "mode_neutral"
API_NAMESPACE = PLUGIN_NAME
PLUGIN_VERSION = "0.1.0"
PROTOCOL_VERSION = 11
METADATA_FINGERPRINT = 0x0C529403FE42B21F
HAS_INITIALIZE = False
HAS_SHUTDOWN = False
CONFIGURATION_SCHEMA_VERSION = 0
CONFIGURATION_FINGERPRINT = None


class GeneratedOperation(NamedTuple):
    operation_id: int
    name: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    scalars: tuple[str, ...]
    dynamic_outputs: tuple[str, ...]
    internal: bool


OPERATIONS = (
    GeneratedOperation(
        101,
        "scale",
        ("a",),
        ("result",),
        ("factor",),
        (),
        False,
    ),
)
OPERATIONS_BY_NAME = MappingProxyType({item.name: item for item in OPERATIONS})
Implementation = Callable[..., None]


def _adapt_scale(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.scalars[0], context.outputs[0])

    return handler


_OPERATION_NAMES = frozenset(
    {
        "scale",
    }
)


def bind_operations(
    implementations: Mapping[str, Implementation],
) -> dict[str, OperationHandler]:
    if set(implementations) != _OPERATION_NAMES:
        missing = sorted(_OPERATION_NAMES - set(implementations))
        unknown = sorted(set(implementations) - _OPERATION_NAMES)
        raise ValueError(
            f"Implementations do not match generated metadata: "
            f"missing={missing}, unknown={unknown}"
        )
    return {
        "scale": _adapt_scale(implementations["scale"]),
    }
