# Generated by wmfs-tool. Do not edit.
import json
from collections.abc import Callable, Mapping
from types import MappingProxyType
from typing import TYPE_CHECKING, NamedTuple

from wmfs_plugin.invocation import InvocationContext

if TYPE_CHECKING:
    from wmfs_plugin.worker import OperationHandler
else:
    OperationHandler = Callable[[InvocationContext], None]

PLUGIN_NAME = "mode_neutral"
API_NAMESPACE = PLUGIN_NAME
PLUGIN_VERSION = "0.1.0"
PROTOCOL_VERSION = 11
METADATA_FINGERPRINT = 0x0C529403FE42B21F
INTERFACE_FINGERPRINT_SHA256 = bytes.fromhex(
    "3d99fd50a9bfeb293cb4304513908266af4519bc7965f262015554d58743f3f9"
)
OPERATION_COUNT = 1
STARTUP_CAPABILITIES = 55
HAS_INITIALIZE = False
HAS_SHUTDOWN = False
CONFIGURATION_SCHEMA_VERSION = 0
CONFIGURATION_FINGERPRINT = None
CONFIGURATION_FINGERPRINT_SHA256 = (
    bytes.fromhex(CONFIGURATION_FINGERPRINT.removeprefix("sha256:"))
    if CONFIGURATION_FINGERPRINT
    else bytes(32)
)
WORKER_DECLARATIONS = json.loads(
    '[{"operation_id":101,"name":"scale","internal":false,"inputs":[{"name":"a","access":"read_only","dtype_variable":"T","dtypes":[]}],"outputs":[{"name":"result","allocation":"known","dimensions":[],"same_shape_as_input":0,"dtype":{"kind":"variable","input":null,"scalar":null,"value":null,"variable":"T"}}],"scalars":[{"name":"factor","kind":"float64","required":true,"default":null,"enum":null,"enum_values":[]}],"vjp":null,"dtype_variables":[{"name":"T","dtypes":["float32","float64"]}]}]'
)


class GeneratedOperation(NamedTuple):
    operation_id: int
    name: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    scalars: tuple[str, ...]
    dynamic_outputs: tuple[str, ...]
    internal: bool


OPERATIONS = (
    GeneratedOperation(
        101,
        "scale",
        ("a",),
        ("result",),
        ("factor",),
        (),
        False,
    ),
)
OPERATIONS_BY_NAME = MappingProxyType({item.name: item for item in OPERATIONS})
Implementation = Callable[..., None]


class BoundOperations(dict[str, OperationHandler]):
    plugin_name = PLUGIN_NAME
    plugin_version = PLUGIN_VERSION
    protocol_version = PROTOCOL_VERSION
    metadata_fingerprint = METADATA_FINGERPRINT
    interface_fingerprint = INTERFACE_FINGERPRINT_SHA256
    configuration_schema_version = CONFIGURATION_SCHEMA_VERSION
    configuration_fingerprint = CONFIGURATION_FINGERPRINT_SHA256
    operation_count = OPERATION_COUNT
    startup_capabilities = STARTUP_CAPABILITIES
    declarations = WORKER_DECLARATIONS

    def __init__(self, *args, initialize=None, shutdown=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.initialize = initialize
        self.shutdown = shutdown


def _adapt_scale(implementation: Implementation) -> OperationHandler:
    def handler(context: InvocationContext) -> None:
        implementation(context.inputs[0], context.scalars[0], context.outputs[0])

    return handler


_OPERATION_NAMES = frozenset(
    {
        "scale",
    }
)


def bind_plugin(
    implementations: Mapping[str, Implementation],
    *,
    initialize=None,
    shutdown=None,
) -> BoundOperations:
    if HAS_INITIALIZE != callable(initialize):
        raise ValueError("initialize hook does not match generated lifecycle")
    if HAS_SHUTDOWN != callable(shutdown):
        raise ValueError("shutdown hook does not match generated lifecycle")
    if set(implementations) != _OPERATION_NAMES:
        missing = sorted(_OPERATION_NAMES - set(implementations))
        unknown = sorted(set(implementations) - _OPERATION_NAMES)
        raise ValueError(
            f"Implementations do not match generated metadata: "
            f"missing={missing}, unknown={unknown}"
        )
    return BoundOperations(
        {
            "scale": _adapt_scale(implementations["scale"]),
        },
        initialize=initialize,
        shutdown=shutdown,
    )


def bind_operations(
    implementations: Mapping[str, Implementation],
) -> BoundOperations:
    if set(implementations) != _OPERATION_NAMES:
        missing = sorted(_OPERATION_NAMES - set(implementations))
        unknown = sorted(set(implementations) - _OPERATION_NAMES)
        raise ValueError(
            f"Implementations do not match generated metadata: "
            f"missing={missing}, unknown={unknown}"
        )
    return BoundOperations(
        {
            "scale": _adapt_scale(implementations["scale"]),
        }
    )
